spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    password: knou4project
  #    url: jdbc:mysql://localhost:3306/knou4project
  #    username: knou4project
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    cache: false
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ENC(8CMdAGSaM94q4KdDhBklsTesm2+wH27i2JL+UwzW04oxpghF9T7l8O0pxzhgzSGpMitep76Kxgy/0L4AzpC6YQ==)