spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: knou4project
#    url: jdbc:mysql://localhost:3306/knou4project
#    username: knou4project
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    cache: false
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
    org.apache.http: DEBUG
    httpclient.wire: DEBUG
server:
  servlet:
    encoding:
      force-response: true
#aladin:
#  requesturl: http://www.aladin.co.kr/ttb/api/ItemSearch.aspx?ttbkey=ttbgreenkey201608001&Query={bookSearchKeyword}&QueryType=Title&MaxResults=10&start=1&SearchTarget=Book&output=js&Version=20131101
api-key:
  chat-gpt: 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
